output_folder: /project/scratch/p200177/DE_371/angeliquebonamy/results/scenarios/BONS/mse/scores/all_scores/expe_obj #  [Rien signif, Espagne,Centre Médit, Jura_Alpes_Drôme-N,Massif-C Sud] name of the parent folder where all experiments will be stored
    # scenarios = ['Alpes-Mar_Golfe-G','Cevennes_Gard_Hérault-N','Corse O','Rien signif','Espagne','Espagne_Roussillon','Centre Médit','Jura_Alpes_Drôme-N','Massif-C Sud','Massif-C Centre','Pyrénées','Var_PACA Ouest_Drôme-S']
experiments: #list of experiments
  - name: Experiment_area1 # the name is a unique identifier to each experiment
    dataloaders:
      type: RandomDataloader
      batch_size: 1
      maxNsamples: 16800
      path_to_csv: /project/scratch/p200177/DE_371/angeliquebonamy/data_basile
      csv_file: IS_labels_bootstrap_no_duplicates.csv
      date_start: '2020-08-13'
      date_end: '2022-08-15'
      number_of_dates : 151
      Lead_Times : 15
      start_time : 21 # 21:00. Arome simulations in the dataset start at 21:00 
      dh : 3
      N_ens : 112
      inv_step : 1000
      cond_members : 16 
      real_dataset_config:
        data_folder: /project/scratch/p200177/DE_371/angeliquebonamy/data_basile
        variables: ['rr','u','v','t2m']
        sizeH: 256
        sizeW: 256
        filename_format: _sample{index}
        file_size: 1
        var_indices: [0,1,2,3] #where to find the variables in dataset samples
        crop_indices: [0,256,0,256]
        preprocessor_config:
          type: Preprocessor
          multi_timestep_mode: True
          nb_timesteps: 15
          timestep_period: 3
          stack_sample_along_time_and_variable: True
          real_var_indices: [0,1,2,3] #where to find the variables in stat files
          real_data_dir: /project/scratch/p200177/DE_371/angeliquebonamy/data_basile
          stat_folder: "stat_files/"
          stat_version: "rr" # the name of the stat file is for ex: 'mean_[stat_version]_log_ppx.npy'
          rr_transform:
            log_transform_iteration: 1
            symetrization: False
            gaussian_std: 0 # Threshold between rain and no rain to add a gaussian noise where rr < gaussian_std.
          normalization:
            type: "minmax"
            per_pixel: False
            for_rr:
              blur_iteration: 1
      fake_dataset_config:
        type: RandomDataset
        data_folder: /project/scratch/p200177/DE_371/angeliquebonamy/results/scenarios/BONS/amse/scores/all_pack
        variables: ['rr','u','v','t2m']
        sizeH: 256
        sizeW: 256
        filename_format: __sample__{index}
        file_size: 16
        var_indices: [0,1,2,3] #where to find the variables in dataset samples
        crop_indices: [0,256,0,256]
        preprocessor_config:
          type: ReverserrPreprocessor
          multi_timestep_mode: True
          nb_timesteps: 15
          timestep_period: 3
          stack_sample_along_time_and_variable: True
          real_var_indices: [0,1,2,3] #where to find the variables in stat files
          real_data_dir: /project/scratch/p200177/DE_371/angeliquebonamy/data_basile
          stat_folder: "stat_files/"
          stat_version: "rr" # the name of the stat file is for ex: 'mean_[stat_version]_log_ppx.npy'
          rr_transform:
            log_transform_iteration: 1
            symetrization: False
            gaussian_std: 0
          normalization:
            type: "minmax"
            per_pixel: False
            for_rr:
              blur_iteration: 1
      obs_dataset_config:
        data_folder: /project/home/p200177/DE_371/datasets/dataset_Meteo_France/obs_databases/
        crop_indices: [180, 436, 500, 756]
        variables: ['ff','dd','t2m']
        var_indices: [0,1,2,3]
        preprocessor_config:
            type: Preprocessor
    metrics:
      args:
        debiasing: False
        debiasing_mode: ENSAVG
        conditioning_members: 16
        threshold: [[ 1.39, 2.78, 4.17, 5.56, 8.33, 11.11 ], [ 278.15, 283.15, 288.15, 293.15, 297.15, 303.15 ]] ## [ff], [t2m] 
        var_channel: 1
        obs_var_channel: 1
        isOnReal: False
        lon_min: 540
        lat_min: 120
        sizeH: 256
        sizeW: 256
      metrics_list:
        # - name: SWD
        #   type: SWDall
        # # - name: MultivarCorr
        # #   type: MultivarCorr
        # - name: spectralCompute
        #   type: spectralCompute
        # # - name: rankHistogram
        # #   type: rankHistogram
        - name: ObjectsAttribution
          type: ObjectsAttribution
        # - name: AreaProportion
        #   rr_idx: 0
        #   type: AreaProportion

  
  
  - name: Experiment_area2 # the name is a unique identifier to each experiment
    dataloaders:
      type: RandomDataloader
      batch_size: 1
      maxNsamples: 16800
      path_to_csv: /project/scratch/p200177/DE_371/angeliquebonamy/data_basile
      csv_file: IS_labels_bootstrap_no_duplicates.csv
      date_start: '2020-08-13'
      date_end: '2022-08-15'
      number_of_dates : 151
      Lead_Times : 15
      start_time : 21 # 21:00. Arome simulations in the dataset start at 21:00 
      dh : 3
      N_ens : 112
      inv_step : 1000
      cond_members : 16 
      real_dataset_config:
        data_folder: /project/scratch/p200177/DE_371/angeliquebonamy/data_basile
        variables: ['rr','u','v','t2m']
        sizeH: 256
        sizeW: 256
        filename_format: _sample{index}
        file_size: 1
        var_indices: [0,1,2,3] #where to find the variables in dataset samples
        crop_indices: [0,256,0,256]
        preprocessor_config:
          type: Preprocessor
          multi_timestep_mode: True
          nb_timesteps: 15
          timestep_period: 3
          stack_sample_along_time_and_variable: True
          real_var_indices: [0,1,2,3] #where to find the variables in stat files
          real_data_dir: /project/scratch/p200177/DE_371/angeliquebonamy/data_basile
          stat_folder: "stat_files/"
          stat_version: "rr" # the name of the stat file is for ex: 'mean_[stat_version]_log_ppx.npy'
          rr_transform:
            log_transform_iteration: 1
            symetrization: False
            gaussian_std: 0 # Threshold between rain and no rain to add a gaussian noise where rr < gaussian_std.
          normalization:
            type: "minmax"
            per_pixel: False
            for_rr:
              blur_iteration: 1
      fake_dataset_config:
        type: RandomDataset
        data_folder: /project/scratch/p200177/DE_371/angeliquebonamy/results/scenarios/BONS/mse/scores/all_inv
        variables: ['rr','u','v','t2m']
        sizeH: 256
        sizeW: 256
        filename_format: __sample__{index}
        file_size: 16
        var_indices: [0,1,2,3] #where to find the variables in dataset samples
        crop_indices: [0,256,0,256]
        preprocessor_config:
          type: ReverserrPreprocessor
          multi_timestep_mode: True
          nb_timesteps: 15
          timestep_period: 3
          stack_sample_along_time_and_variable: True
          real_var_indices: [0,1,2,3] #where to find the variables in stat files
          real_data_dir: /project/scratch/p200177/DE_371/angeliquebonamy/data_basile
          stat_folder: "stat_files/"
          stat_version: "rr" # the name of the stat file is for ex: 'mean_[stat_version]_log_ppx.npy'
          rr_transform:
            log_transform_iteration: 1
            symetrization: False
            gaussian_std: 0
          normalization:
            type: "minmax"
            per_pixel: False
            for_rr:
              blur_iteration: 1
      obs_dataset_config:
        data_folder: /project/home/p200177/DE_371/datasets/dataset_Meteo_France/obs_databases/
        crop_indices: [180, 436, 500, 756]
        variables: ['ff','dd','t2m']
        var_indices: [0,1,2,3]
        preprocessor_config:
            type: Preprocessor
    metrics:
      args:
        debiasing: False
        debiasing_mode: ENSAVG
        conditioning_members: 16
        threshold: [[ 1.39, 2.78, 4.17, 5.56, 8.33, 11.11 ], [ 278.15, 283.15, 288.15, 293.15, 297.15, 303.15 ]] ## [ff], [t2m] 
        var_channel: 1
        obs_var_channel: 1
        isOnReal: False
        lon_min: 540
        lat_min: 120
        sizeH: 256
        sizeW: 256
      metrics_list:
        # - name: SWD
        #   type: SWDall
        # # - name: MultivarCorr
        # #   type: MultivarCorr
        # - name: spectralCompute
        #   type: spectralCompute
        # # - name: rankHistogram
        # #   type: rankHistogram
        - name: ObjectsAttribution
          type: ObjectsAttribution
        # - name: AreaProportion
        #   rr_idx: 0
        #   type: AreaProportion