output_plots: /home/users/u101957/DE371_MetScore/experiments15/experiment_plots
experiments:  
  - name: 'Experiment1'
    short_name: "AROME"
    N_ens: 16
  - name: 'Experiment2'
    short_name: "Inversion"
    N_ens: 112
  - name: 'Experiment3'
    short_name: "Perturbation"
    N_ens: 112

metrics:

  - name: skillSpread
    folder: skillSpread
  - name: biasEnsemble
    folder: biasEnsemble
  - name: rankHistogram
    folder: rankHistogram
  - name: brierScore
    folder: brierScore
  - name: relDiagram
    folder: relDiagram
  - name: spectralCompute
    folder: spectralCompute
  - name: MultivarCorr
    folder: MultivarCorr
  - name: Quantiles
    folder: Quantiles
    qlist: [0.05,0.5,0.8,0.9]
  - name: QuantilesScore
    folder: QuantilesScore
    qlist: [0.01,0.1,0.9,0.99]
  
expe_folder: /home/users/u101957/DE371_MetScore/experiments15
number_dates : 30
lead_times : 14
var_number : 3
size_H : 256
size_W : 256
N_bins_max: 121
N_bins_max_real: 17
