output_plots: /project/scratch/p200177/DE_371/angeliquebonamy/results/dates/GOOD_DATA/scores_/plots
experiments:  
  - name: 'Experiment1'
    short_name: "Arome"
    N_ens: 16
  - name: 'amse'
    short_name: "AMSE"
    N_ens: 112
  - name: 'amse_vgg'
    short_name: "inv AMSE vgg"
    N_ens: 112
  - name: 'vgg'
    short_name: "Perceptual loss"
    N_ens: 112
  # - name: 'Perturbation_vgg_16' 
  #   short_name: "Pertub Perceptual loss"
  #   N_ens: 112
  # - name: 'Perturbation_amse_vgg_16' 
  #   short_name: "Pertub AMSE VGG"
  #   N_ens: 112
  # - name: 'Experiment3'
  #   short_name: "Rough"
  #   N_ens: 112
  # - name: 'AROME_bootstrap'
  #   short_name: "AROME"
  #   N_ens: 112
  # - name: 'AROME_test_4'
  #   short_name: "AROME_test_4"
  #   N_ens: 112
  # - name: 'AROME_test_8'
  #   short_name: "AROME_test_8 "
  #   N_ens: 112
  # - name: 'Experiment4'
  #   short_name: "Filter"
  #   N_ens: 112
  # # - name: 'Experiment6'
  # #   short_name: "mul_pixel_loss_mse"
  # #   N_ens: 112
  # - name: 'Experiment_sol5_noise_rdm'
  #   short_name: "WAMSE sol5noise - rdm  "
  #   N_ens: 112
  # - name: 'Experiment_sol5_noise_tr'
  #   short_name: "WAMSE sol5noise tr"
  #   N_ens: 112
  # - name: 'Experiment_sol5_tr'
  #   short_name: "WAMSE sol5 tr"
  #   N_ens: 112
  # - name: 'Experiment8'
  #   short_name: "mse sol5 rdm"
  #   N_ens: 112
  # - name: 'Experiment9'
  #   short_name: "wmse sol5 rdm "
  #   N_ens: 112
  # - name: 'Experiment11'
  #   short_name: "sc"
  #   N_ens: 112
  # - name: 'Experiment12'
  #   short_name: "sc"
  #   N_ens: 112
  # - name: 'Experiment13'
  #   short_name: "sc"
  #   N_ens: 112


metrics:
  # - name: spectralCompute
    # folder: spectralCompute
  # # - name: MultivarCorr
  # #   folder: MultivarCorr
  # # # - name: Quantiles
  # # #   folder: Quantiles
  # # #   qlist: [0.05,0.5,0.8,0.9]
  # # # - name: QuantilesScore
  # # #   folder: QuantilesScore
  # # #   qlist: [0.01,0.1,0.9,0.99]
  # - name: SWD
    # folder: SWDall
  # - name: ObjectsAttribution
  #   folder : ObjectsAttribution
  # - name : AreaProportion
    # folder : AreaProportion 
  - name: biasEnsemble
    folder: biasEnsemble
  # - name: ensembleCRPS
  #   folder: ensembleCRPS
  # - name: skillSpread
  #   folder: skillSpread
expe_folder: /project/scratch/p200177/DE_371/angeliquebonamy/results/dates/GOOD_DATA/scores_
number_dates : 13
lead_times : 15
var_number : 4
size_H : 256
size_W : 256
N_bins_max: 121
N_bins_max_real: 17
    