output_plots: /home/users/u101957/DE371_MetScore/tests_scores/plots_tests21/
experiments:  

  - name: 'Experiment_vgg'
    short_name: "Experiment1"
    N_ens: 16

  - name: 'sigmoid_stdmean_rruvt_pca_8_spr_1.0'
    short_name: "sigmoid_stdmean_pca_8_spr_1.0"
    N_ens: 112
  # - name: 'sigmoid_stdmean_rruvt_pca_8_spr_1.2'
  #   short_name: "sigmoid_stdmean_pca_8_spr_1.2"
  #   N_ens: 112  

  - name: 'sigmoid_stdmean_rruvt_pca_10_spr_1.0'
    short_name: "sigmoid_stdmean_pca_10_spr_1.0"
    N_ens: 112
  # - name: 'sigmoid_stdmean_rruvt_pca_10_spr_1.2'
  #   short_name: "sigmoid_stdmean_pca_10_spr_1.2"
  #   N_ens: 112 

  # - name: 'sigmoid_stdmean_rruvt_pca_8_spr_1.3'
  #   short_name: "pca_8_spr_1.3"
  #   N_ens: 112
  # - name: 'sigmoid_stdmean_rruvt_pca_8_spr_1.25'
  #   short_name: "pca_8_spr_1.25"
  #   N_ens: 112

  # - name: 'sigmoid_betax1.5'
  #   short_name: "sigmoid_betax1.5"
  #   N_ens: 112
  # - name: 'sigmoid_quantile_rr_stdmean_uvt_pca_10_spr_1.0'
  #   short_name: "quantile_sigmoid_pca_10_spr_1.0"
  #   N_ens: 112
  # - name: 'sigmoid_quantile_rr_stdmean_uvt_pca_10_spr_1.2'
  #   short_name: "quantile_sigmoid_pca_10_spr_1.2"
  #   N_ens: 112  

  # - name: 'sigmoid_quantile_rr_stdmean_uvt_pca_8_spr_1.0'
  #   short_name: "quantile_sigmoid_pca_8_spr_1.0"
  #   N_ens: 112
  # - name: 'sigmoid_quantile_rr_stdmean_uvt_pca_8_spr_1.2'
  #   short_name: "quantile_sigmoid_pca_8_spr_1.0"
  #   N_ens: 112  
  # - name: 'sigmoid_quantile_rr_stdmean_uvt_pca_10_spr_1.5'
  #   short_name: "pca_10_spr_1.5"
  #   N_ens: 112

  # - name: 'sigmoid_quantile_rr_stdmean_uvt_pca_12_spr_1.0'
  #   short_name: "pca_12_spr_1.0"
  #   N_ens: 112
  # - name: 'sigmoid_quantile_rr_stdmean_uvt_pca_12_spr_1.2'
  #   short_name: "pca_12_spr_1.2"
  #   N_ens: 112  
  # - name: 'sigmoid_quantile_rr_stdmean_uvt_pca_12_spr_1.5'
  #   short_name: "pca_12_spr_1.5"
  #   N_ens: 112

  # - name: 'sigmoid_quantile_rr_stdmean_uvt_pca_14_spr_1.0'
  #   short_name: "pca_14_spr_1.0"
  #   N_ens: 112
  # - name: 'sigmoid_quantile_rr_stdmean_uvt_pca_14_spr_1.2'
  #   short_name: "pca_14_spr_1.2"
  #   N_ens: 112  
  # - name: 'sigmoid_quantile_rr_stdmean_uvt_pca_14_spr_1.5'
  #   short_name: "pca_14_spr_1.5"
  #   N_ens: 112

  # - name: 'sigmoid_huber_rruvt'
  #   short_name: "sigmoid_huber_rruvt"
  #   N_ens: 112
  # - name: 'sigmoid_huber_stdmean_rruvt'
  #   short_name: "sigmoid_huber_stdmean_rruvt"
  #   N_ens: 112

  # - name: 'pert_init'
  #   short_name: "pert_init"
  #   N_ens: 112
  - name: 'linear'
    short_name: "linear"
    N_ens: 112

  # - name: 'sigmoid_inflate_rdm'
  #   short_name: "sigmoid_inflate_rdm"
  #   N_ens: 112
  # - name: 'sigmoid_scut14' 
  #   short_name: "sigmoid_scut_14"
  #   N_ens: 112
  # - name: 'sigmoid_rr_uvt_stdmean'
  #   short_name: "sigmoid_rr_uvt_stdmean"
  #   N_ens: 112
  # - name: 'sigmoid' 
  #   short_name: "sigmoid"
  #   N_ens: 112

  # - name: 'quantile_rr_sigmoid' 
  #   short_name: "quantile_rr_sigmoid"
  #   N_ens: 112


  - name: 'pert_init'
    short_name: "pert_init"
    N_ens: 112


metrics:
  # - name: spectralCompute
    # folder: spectralCompute
  # # - name: MultivarCorr
  # #   folder: MultivarCorr
  # # # - name: Quantiles
  # # #   folder: Quantiles
  # # #   qlist: [0.05,0.5,0.8,0.9]
  # # # - name: QuantilesScore
  # # #   folder: QuantilesScore
  # # #   qlist: [0.01,0.1,0.9,0.99]
  # - name: SWD
    # folder: SWDall
  # - name: ObjectsAttribution
    # folder : ObjectsAttribution
  # - name : AreaProportion
  #   folder : AreaProportion 
  # - name: biasEnsemble
  #   folder: biasEnsemble
  - name: ensembleCRPS
    folder: ensembleCRPS
  - name: skillSpread
    folder: skillSpread
expe_folder: /home/users/u101957/DE371_MetScore/tests_scores
number_dates : 20
lead_times : 15
var_number : 4
size_H : 256
size_W : 256
N_bins_max: 121
N_bins_max_real: 17
