output_plots: /home/users/u101957/DE371_MetScore/isonreal72/plot_pert_inv 
experiments:  
  # - name: 'AROME'
  #   short_name: "Arome"
  #   N_ens: 16
  - name: 'Experiment1'
    short_name: "AROME"
    N_ens: 112
  # - name: 'Experiment2'
  #   short_name: "inv AMSE  "
  #   N_ens: 112
  # - name: 'Arome_vgg'
  #   short_name: "AROME"
  #   N_ens: 112
  - name: 'Experiment_vgg'
    short_name: "inv Perceptual loss"
    N_ens: 112
  - name: 'Perturbation_vgg_16' 
    short_name: "Pertub Perceptual loss"
    N_ens: 112
  # - name: 'Perturbation_amse_16' 
  #   short_name: "Pertub AMSE"
  #   N_ens: 112
  # - name: 'Experiment3'
  #   short_name: "Perceptual loss"
  #   N_ens: 112
  # - name: 'AROME_bootstrap'
  #   short_name: "AROME"
  #   N_ens: 112
  # - name: 'AROME_test_4'
  #   short_name: "AROME_test_4"
  #   N_ens: 112
  # - name: 'AROME_test_8'
  #   short_name: "AROME_test_8 "
  #   N_ens: 112
  # # - name: 'Experiment5'
  # #   short_name: "mul_pixel_loss_mae"
  # #   N_ens: 112
  # # - name: 'Experiment6'
  # #   short_name: "mul_pixel_loss_mse"
  # #   N_ens: 112
  # - name: 'Experiment_sol5_noise_rdm'
  #   short_name: "WAMSE sol5noise - rdm  "
  #   N_ens: 112
  # - name: 'Experiment_sol5_noise_tr'
  #   short_name: "WAMSE sol5noise tr"
  #   N_ens: 112
  # - name: 'Experiment_sol5_tr'
  #   short_name: "WAMSE sol5 tr"
  #   N_ens: 112
  # - name: 'Experiment8'
  #   short_name: "mse sol5 rdm"
  #   N_ens: 112
  # - name: 'Experiment9'
  #   short_name: "wmse sol5 rdm "
  #   N_ens: 112
  # - name: 'Experiment11'
  #   short_name: "sc"
  #   N_ens: 112
  # - name: 'Experiment12'
  #   short_name: "sc"
  #   N_ens: 112
  # - name: 'Experiment13'
  #   short_name: "sc"
  #   N_ens: 112


metrics:
  # - name: spectralCompute
  #   folder: spectralCompute
  # # - name: MultivarCorr
  # #   folder: MultivarCorr
  # # # - name: Quantiles
  # # #   folder: Quantiles
  # # #   qlist: [0.05,0.5,0.8,0.9]
  # # # - name: QuantilesScore
  # # #   folder: QuantilesScore
  # # #   qlist: [0.01,0.1,0.9,0.99]
  # - name: SWD
    # folder: SWDall
  # - name: ObjectsAttribution
  #   folder : ObjectsAttribution
  # - name : AreaProportion
  #   folder : AreaProportion 
  - name: biasEnsemble
    folder: biasEnsemble
  - name: ensembleCRPS
    folder: ensembleCRPS
  - name: skillSpread
    folder: skillSpread
expe_folder: /home/users/u101957/DE371_MetScore/isonreal72
number_dates : 35
lead_times : 15
var_number : 4
size_H : 256
size_W : 256
N_bins_max: 121
N_bins_max_real: 17
    