output_folder: /home/users/u101957/DE371_MetScore/Score_Eval # name of the parent folder where all experiments will be stored
experiments: #list of experiments
  - name: AROME_conditioned_3h # the name is a unique identifier to each experiment
    dataloaders:
      type: DateDataloader
      batch_size: 1
      maxNsamples: 16384
      path_to_csv: /project/home/p200177/DE_371/datasets/dataset_Meteo_France/IS_1_1.0_0_0_0_0_0_256_large_lt_done
      csv_file: Large_lt_test_labels.csv
      date_start: '2020-06-10'
      date_end: '2022-11-13'
      number_of_dates : 151
      Lead_Times : 15
      start_time : 21 # 21:00. Arome simulations in the dataset start at 21:00 
      dh : 3
      N_ens : 1
      inv_step : 1000
      cond_members : 16 
      real_dataset_config:
        data_folder: /project/home/p200177/DE_371/datasets/dataset_Meteo_France/IS_1_1.0_0_0_0_0_0_256_large_lt_done
        variables: ['u','v','t2m']
        sizeH: 256
        sizeW: 256
        filename_format: _sample{formatted_index}
        file_size: 1
        var_indices: [1,2,3] #where to find the variables in dataset samples
        crop_indices: [0,256,0,256]
        preprocessor_config:
          type: Preprocessor
      fake_dataset_config:
        type: RealDataset
        data_folder: /project/home/p200177/DE_371/datasets/dataset_Meteo_France/IS_1_1.0_0_0_0_0_0_256_large_lt_done/
        variables: ['u','v','t2m']
        sizeH: 256
        sizeW: 256
        filename_format: _sample{formatted_index}
        file_size: 1 # filesize in fake dataset
        var_indices: [1,2,3] #where to find the variables in dataset samples
        crop_indices: [0,256,0,256]
        preprocessor_config:
          type: Preprocessor
      obs_dataset_config:
        type: ObsDataset
        data_folder: /project/home/p200177/DE_371/datasets/dataset_Meteo_France/obs_databases/
        crop_indices: [180, 436, 500, 756]
        variables: ['ff','dd','t2m']
        var_indices: [1,2,3]
        preprocessor_config:
            type: Preprocessor
    metrics:
      args:
        debiasing: False
        debiasing_mode: ENSAVG
        conditioning_members: 16
        threshold: [[ 1.39, 2.78, 4.17, 5.56, 8.33, 11.11 ], [ 278.15, 283.15, 288.15, 293.15, 297.15, 303.15 ]] ## [ff], [t2m] 
        var_channel: 1
        obs_var_channel: 1
        isOnReal: False
      metrics_list:
        # - name: SWD
        #   type: SWDall
        # - name: MultivarCorr
        #   type: MultivarCorr
        # - name: spectralCompute
        #   type: spectralCompute
        # - name: ensembleCRPS
        #   type: ensembleCRPS
        #   fair: True # this is an additional argument, specific to the ensembleCRPS metric. It should be specified here, but it can also be specified in the args section.
        # - name: brierScore
        #   type: brierScore
        # - name: skillSpread
        #   type: skillSpread
        - name: biasEnsemble
          type: biasEnsemble

  # - name: Conditioned_224_epochs_rho_7_10_steps_large_lt_test_3h_spectral # the name is a unique identifier to each experiment
  #   dataloaders: # defining the sources of data (datasets), their sampling logic and the preprocessing
  #     type: DateDataloader # the type defines the loading logic. DateDataloader separates data into distinct timestamps.
  #     batch_size: 1 # size of samples passed to BATCHED metrics. If one file contains a whole ensemble, then the batch consists in only this ensemble (hence the default number to 1).
  #     maxNsamples: 16384 # maximum number of samples to be used for NON-BATCHED metrics. If it is superior to the total number of samples, the latter will be chosen.
  #     path_to_csv: /project/home/p200177/DE_371/datasets/dataset_Meteo_France/IS_1_1.0_0_0_0_0_0_256_large_lt_done/ #where to find the csv file linking files to metadata. Files not registered in this csv will not be used.
  #     csv_file: Large_lt_test_labels.csv  # the csv file. An example structure is shown in example_labels.csv
  #     date_start: '2019-08-14' # defining the period in which data is fetched 
  #     date_end: '2023-08-15' # this period can be any size. This is used e.g to restrict the dates selected in the csv file.
  #     number_of_dates : 151 # Number of dates to be selected within de defined period. The order of selection is fixed and depends on the ordering of the csv.
  #     # number_of_dates : 151 # for 3h reduced
  #     # Lead_Times : 45 # number of lead times that are considered for each forecast
  #     Lead_Times : 15 # for 3h reduced
  #     start_time : 21 # 21:00. Arome simulations in the dataset start at 21:00
  #     # dh : 1 # Lead time step. This is used to match observation sources
  #     dh : 3 # for 3h reduced
  #     real_dataset_config: # defining the Dataset for "real" (physics-based NWP) reference.
  #       data_folder: /project/home/p200177/DE_371/datasets/dataset_Meteo_France/IS_1_1.0_0_0_0_0_0_256_large_lt_done/ #
  #       variables: ['u','v','t2m'] # list of strings, to name the variables considered
  #       sizeH: 256  #size in latitude ("height")
  #       sizeW: 256  #size in latitude ("height")
  #       var_indices: [1,2,3] #indices to find the variables in dataset samples (usually, in a channel-first view). each element of "variables" is mapped to one element of var_indices, here 'u':1, 'v':2, 't2m':3
  #       crop_indices: [0,256,0,256] # to perform any crop (latitude indices first)
  #       preprocessor_config:
  #         type: Preprocessor # base preprocessor class by default ("real" samples are not preprocessed)

  #     fake_dataset_config:
  #       type: FakeDataset
  #       data_folder: /project/scratch/p200177/DE_371/maxencelame/results/samples_conditioned/run_conditioned_224_epochs_ED_rho_7_10_steps_3h/batched_samples_0
  #       variables: ['u','v','t2m']
  #       sizeH: 256
  #       sizeW: 256
  #       filename_format: 4var_fake_ensemble_{date}_{formatted_index}
  #       file_size: 1 # filesize in fake dataset
  #       var_indices: [1,2,3] #where to find the variables in dataset samples
  #       crop_indices: [0,256,0,256]
  #       preprocessor_config:
  #         type: ReverserrPreprocessor
  #         real_var_indices: [0,1,2,3] #where to find the variables in stat files
  #         real_data_dir: /project/home/p200177/DE_371/datasets/dataset_Meteo_France/IS_1_1.0_0_0_0_0_0_256_large_lt_done/
  #         stat_folder:  /project/home/p200177/DE_371/datasets/dataset_Meteo_France/IS_1_1.0_0_0_0_0_0_256_large_lt_done/stat_files_Massif_Central/  
  #         stat_version: "rr" # the name of the stat file is for ex: 'mean_[stat_version]_log_ppx.npy'
  #         rr_transform:
  #           log_transform_iteration: 1
  #           symetrization: False
  #           gaussian_std: 0
  #         normalization:
  #           type: "mean"
  #           per_pixel: false
  #           for_rr:
  #             blur_iteration: 1
  #     obs_dataset_config:
  #       data_folder: /project/home/p200177/DE_371/datasets/dataset_Meteo_France/obs_databases/
  #       crop_indices: [180, 436, 500, 756]
  #       variables: ['ff','dd','t2m']
  #       var_indices: [0,1,2]
  #       preprocessor_config:
  #           type: Preprocessor
  #   metrics:
  #     args:
  #       debiasing: False
  #       conditioning_members: 16
  #       threshold: [[ 1.39, 2.78, 4.17, 5.56, 8.33, 11.11 ], [ 278.15, 283.15, 288.15, 293.15, 297.15, 303.15 ]] ## [ff], [t2m] 
  #       var_channel: 1
  #       obs_var_channel: 1
  #       isOnReal: False
  #     metrics_list:
  #       # - name: SWD
  #       #   type: SWDall
  #       # - name: ensembleCRPS
  #       #   type: ensembleCRPS
  #       #   fair: True # this is an additional argument, specific to the ensembleCRPS metric. It should be specified here, but it can also be specified in the args section.
  #       # - name: skillSpread
  #       #   type: skillSpread
  #       # - name: biasEnsemble
  #       #   type: biasEnsemble
  #       # - name: rankHistogram
  #       #   type: rankHistogram
  #       # - name: brierScore
  #       #   type: brierScore
  #       # - name: relDiagram
  #       #   type: relDiagram
  #       - name: spectralCompute
  #         type: spectralCompute
  #       # - name: spectralDist
  #       #   type: spectralDist
  #       # - name: MultivarCorr
  #       #   type: MultivarCorr
  #       # - name: Quantiles
  #       #   type: Quantiles
  #       #   qlist: [0.05,0.5,0.8,0.9]
  #       # - name: QuantilesScore
  #       #   type: QuantilesScore
  #       #   qlist: [0.01,0.1,0.9,0.99]
